Add readme in french
crim-ca/FrVD pull request #1
Opened 2021-07-08 13:25 UTC by EdGaCan

2021-07-08 14:39 UTC, fmigneault requested changes

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +Un jeu de données de références de clips video, de videodescriptions (VD), et de métadonnées (scène, personnage, actions)
J'enlèverais (ou reformulerais) le `clips video` car ceux-ci ne sont pas inclus dans le dataset et il faudrait éviter ce genre d'attentes.

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +Accompagné d'un utilitaire de visualisation des clips vidéos, des vidéosdescriptions et des actions.
On dirait que cette phrase manque une information.

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +Dans le cadre d'un partenariat avec le Fond d'accessibilité à la radiodiffusion (le FAR), nous avons voulu enrichir
enlever "le" dans la parenthèse

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +automatique et/ou pour la détection d'éléments visuels (scène, personnage, action)
Manque un point de fin de phrase.

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +Pour ce faire, nous avons détecté les actions dans les clips vidéos via un modèle vidéo d'apprentissage automatique (SlowFast)
utiliser une référence markdown pour SlowFast: 
```
[SlowFast][SlowFast]

[SlowFast]: https://github.com/facebookresearch/SlowFast
```

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +- les `références` aux clips vidéos ( film ou télésérie)
enlever l'espace après `(`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +    - la `vidédescriptions` rédigée manuellement en FR
enlever `s`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +    - des `annotations linguistiques` classiques (librairie Stanza) : segmentation de la VD en phrase, jetons, catégorie grammaticales,
ajouter une référence markdown pour `Stanza`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +    indice de position des jetons
manque 2 espaces pour aligner avec le texte de la ligne du dessus

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +    - les `actions du jeu de données AVA détectées en se basant sur les annotations de la VD` (plusieurs méthodes d'alignement sont proposées - voir plus bas)
il faudrait simplifier les items entre ``` `` ``` pour simplifier la lecture de ce qui est mis en emphase
ex: les `actions AVA SlowFast`: ...(description)...

remplacer le `voir plus bas` par 
`[voir plus bas][#<la-section-applicable>`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +      en format IOB ( voir plus bas le cadre d'annotation)
enlever l'espace après `(`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +## Annotations de la VD
utiliser vidéodescription au long dans le titre

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +## Annotations d'actions depuis la VD
utiliser vidéodescription au long dans le titre

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +L'annotation a été faite manuellement sur 45 % du corpus puis les 55% restant sont le résultat d'une annotation
enlever l'espace avant `%`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +automatique après utilisation d'un modèle bi-LSTM entraîné sur les données annotées manuellement.
ajouter une référence markdown pour le `bi-LSTM` ? quel modèle/implémentation ?

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +### Cadre d'annotation
ajouter une ligne après ce titre

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +
enlever la ligne excédante

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> + - Entités impliquées dans l’action, en distinguant :
utiliser l'autre caractère d'apostrophe `'`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +    -` objet indirect essentiel`
espace mal placé ```-\` ``` -> ``` - ` ```

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +    en précisant pour chacun son type si c’est un `humain`, un `animal`, un `objet` ou un `concept`.
manque des espace pour l'alignement avec le texte d'item de liste

utiliser l'autre apostrophe dans `c'est`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> + - SlowFast préentraîné sur Kinetics600
alignement incorrect de l'item de liste

utiliser la référence `[SlowFast][SlowFast]` créée plus haut (voir autre commentaire)

il faudrait une référence markdown vers `Kinetics600`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +Implémentation à l’aide de https://github.com/facebookresearch/SlowFast
Peut être enlevé suite à l'ajout des références markdown.

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +- SlowFast préentraîné sur AVA avec améliorations
il faudrait une référence markdown vers `AVA` + celle pour SlowFast

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +Utilisation de detectron2 pour la reconnaissance d’actions par individu plutôt que globales
- ajouter une référence vers https://github.com/facebookresearch/detectron2
- ajuster l'apostrophe
- ajouter le point de fin de phrase

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +Nous avons fait correspondre les annotations d'actions de la VD avec le jeu d'action AVA ( 80 étiquettes).
enlever l'espace après `(`

réutiliser le lien markdown plus haut pour `AVA` (voir autre commentaire)

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> + - filtré et extrait les actions avec sujets humains (avec ou sans objet direct) depuis les annotations de la VD.
enlever l'espace avant le `-`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +- obtenu au final environ ~9 000 actions uniques en français (Ex : _sortir, apercevoir QQUN_, etc.)
enlever l'espace dans `9 000`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +Pour les aligner avec le jeu d'action AVA, plusieurs méthodes ont été explorées, elles apparaissent chacune dans le jeu de données Fr-VD  :
utiliser le lien markdown `AVA`

sépararer en deux phrases à `explorées, elle`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +- utilisation de **plongements lexicaux multilingues** : `Muse`, `fastText` et `SentenceBert`
utiliser des références markdown pour chacun de ces éléments

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +    - `prox` : le degré de proximité sémantique (`1` pour un alignement adéquat, `2` pour un alignement plus relâché , `0` si aucune action AVA ne correspond)
enlever l'espace supplémentaire avant `-` pour aligner les items

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> + - utilisation d'un **alignement fait manuellement** pour les 300 actions les plus fréquentes du corpus ( représente plus de 50% des occurences du corpus) :
supprimer l'espace après `(`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +      Dictionnaire électronique de synonymes, Wonef et WOlf  : `Resslex`
séparer chaque items dans une sous-liste indenté (comme pour le `manuel`/`prox` en-dessous)

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> + - films : _Bon cop, Bad cop_ (policier), _Le démantèlement_ (agriculture), _Ernest et Célestine_ (dessin animé avec des animaux)
enlever l'espace avant `-`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +- téléséries : _La vie en vert_ (écologie), _Habitat_ (construction), _Une galaxie près de chez vous_ (science-fiction loufoque)
utiliser des références markdown vers chacun des films/téléséries listés? 
eg: https://en.wikipedia.org/wiki/Bon_Cop,_Bad_Cop , https://fr.wikipedia.org/wiki/Le_Démantèlement , etc.

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +
enlever les lignes superflues

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +## Contributeurs et remerciements
ajouter une ligne

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +Ces jeux de données ont été produits par Francis Charette-Migneault, Edith Galy, Lise Rebout et Mathieu Provencher du CRIM.
Ajouter un fichier `AUTHORS.md` à la racine avec 

```
# Contributors

- Francis Charette Migneault <@fmigneault>
- Edith Galy <@EdGaCan>
- Lise Rebout <?? handle ??>
- Mathieu Provencher <@MatProv>
```

Puis y faire référence avec ex: `[les contributeurs du CRIM](AUTHORS.md)`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +Le projet a bénéficié du soutien financier du Fond d'accessibilité à la radiodiffusion (FAR).
utiliser un lien markdown?

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +```
remplacer par une référence style
 `Veuillez référencer à l'aide de la [citation suivante](README.md#Citation)`

2021-07-08 14:39 UTC, fmigneault commented on README_French.md
> +- `SentenceBert` : Reimers, Nils, and Iryna Gurevych. 2020. “Making Monolingual Sentence Embeddings Multilingual Using Knowledge Distillation.” arXiv [cs.CL]. arXiv. http://arxiv.org/abs/2004.09813.
déplacer toutes ces références dans un fichier à par `references.md`
nous alors les réutiliser à plusieurs places

2021-08-03 17:40 UTC, EdGaCan commented on README_French.md
> +- obtenu au final environ ~9 000 actions uniques en français (Ex : _sortir, apercevoir QQUN_, etc.)
pas besoin ici

2021-08-03 18:04 UTC, EdGaCan commented on README_French.md
> +      Dictionnaire électronique de synonymes, Wonef et WOlf  : `Resslex`
les 3 ressources sont agrégées dans Resslex donc c'est pas pareil.. ( ou alors je comprends pas ton point ?)

2021-08-03 18:09 UTC, EdGaCan commented on README_French.md
> +
Ici je pensais que tu pouvais rajouter la structure des fichiers, une description formelle ?

2021-08-03 18:09 UTC, EdGaCan commented on README_French.md
> +
Sinon il faut enlever cette section non ?

2021-08-03 19:28 UTC, fmigneault commented on README_French.md
> +    - les `annotations de la VD` : annotations manuelles ou automatiques (précisé selon le cas) des actions et des rôles (sujet, objet)` identifiées dans la VD en format IOB (voir le cadre d'annotati
erreur de format causé par le \` après la parenthèse

2021-08-03 19:28 UTC, fmigneault commented on README_French.md
> +    - la `vidédescription` rédigée manuellement en FR ;
typo `vidé[o]description`

2021-08-03 19:28 UTC, fmigneault commented on README_French.md
> +      [Stanza]: https://stanfordnlp.github.io/stanza/
il ne faut pas d'espace entre `[Stanza] [Stanza]`
la référence doit être alignée a gauche (sans tabulation)

2021-08-03 19:28 UTC, fmigneault commented on README_French.md
> +    - les `annotations de la VD` : annotations manuelles ou automatiques (précisé selon le cas) des actions et des rôles (sujet, objet)` identifiées dans la VD en format IOB (voir le cadre d'annotati
Je pense qu'il faut un `-` à la place des espace dans le lien après `#`
la référence n'est pas créée ici: 
https://github.com/crim-ca/FrVD/blob/readmeFR/README_French.md

2021-08-03 19:28 UTC, fmigneault commented on README_French.md
> +[AVA]: https://research.google.com/ava/
pas besoin de redéfinir le lien

2021-08-03 19:28 UTC, fmigneault commented on README_French.md
> +[SlowFast]: https://github.com/facebookresearch/SlowFast
pas besoin de redéfinir le lien

2021-08-03 19:28 UTC, fmigneault commented on README_French.md
> +
Ok c'est bon.

2021-08-03 19:33 UTC, fmigneault commented on README_French.md
> +[FAR]:https://www.baf-far.ca/fr
pas besoin de redéfinir

2021-08-03 19:33 UTC, fmigneault commented on README_French.md
>  }
ceci n'est plus nécessaire puisque la citation du README principal est employée

2021-08-17 21:05 UTC, merged